---
name: validator
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  collectInputs:
    name: collect workflow inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@v1.4.1

  tfLint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TFLint
        uses: docker://wata727/tflint

  fmt:
    name: code format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:latest
    steps:
      - uses: actions/checkout@master
      - run: |
          terraform fmt --recursive -check=true

  preCommit:
    name: pre-commit-hook
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        run: |
          brew install pre-commit terraform-docs terraform tflint
      - name: validate sources
        run: |
          pre-commit run --all-files
